name: CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/fastapi-key.pem
          chmod 600 ~/.ssh/fastapi-key.pem
          ssh-keyscan -H 13.60.41.102 >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/fastapi-key.pem ubuntu@13.60.41.102 <<'EOF'
          cd /opt/fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
          EOF
