name: CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Deploy Application
        run: |
          ssh ubuntu@13.60.41.102 <<'EOF'
          cd /opt/fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
          EOF
